# Site settings
title: Devfest Fsa 2019
description: Maior evento de desenvolvedores do interior da Bahia
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000"

# Configurações da Página
titulo: Devfest Fsa 2019
descricao: DEV Feira de Sanatana
user_title:

imagem: assets/background.png
imagem_logo_principal: assets/logo.png
imagem_logo: assets/logoicone.png
imagem_logo_mobile: assets/logoicone2.png
imagem_conteudo: assets/background2.png

link_codconduta: https://www.instagram.com/gdgfsaba/?hl=pt
link_subpalestra: https://www.facebook.com/gdgfsaba/
link_venda: https://www.sympla.com.br/gdg-devfest-fsa-2019__614974

contato_email: gdgfsaba@gmail.com
contato_instagram: https://www.instagram.com/gdgfsaba/?hl=pt
contato_facebook: https://www.facebook.com/gdgfsaba/

cor_padrao: rgb(92, 143, 245)

# Sobre o Evento
sobre: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam mi neque, fringilla vitae cursus nec, porta vitae eros. Aliquam facilisis molestie dui ac consequat. Duis et suscipit ipsum. Suspendisse potenti. Etiam suscipit ornare mi. Praesent porta posuere sapien eu aliquam. Curabitur vestibulum consequat nibh, at rhoncus turpis. Aliquam rhoncus metus in lorem suscipit congue. Phasellus non ante ipsum. Pellentesque vel diam dui. Donec dapibus mattis lorem, non ullamcorper arcu scelerisque nec. In euismod nulla a libero interdum sagittis. Vestibulum ultrices semper lacus, in tempor lorem maximus eu. Suspendisse posuere orci in ipsum congue, a elementum tortor semper. Vestibulum eget ipsum vel purus posuere placerat. Nam mattis eros a tincidunt bibendum. Pellentesque faucibus metus vitae dui varius bibendum. Etiam sed pellentesque felis. Aliquam a tortor ut sem fermentum pulvinar. Integer bibendum massa id tellus tempor consequat. Integer et mollis augue, id convallis lorem. Nam iaculis egestas diam nec iaculis. Curabitur a finibus tellus, at tempus lacus. Maecenas eget lectus sed enim ultricies rutrum nec at quam. Maecenas posuere volutpat facilisis. Integer sed consectetur mi.

# Patrocinadores
patrocinadores:
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: https://www.instagram.com/mandacaruhs/
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: https://www.instagram.com/mandacaruhs/
# Apoio

apoio:
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: https://www.instagram.com/mandacaruhs/
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: https://www.instagram.com/mandacaruhs/
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: https://www.instagram.com/mandacaruhs/

# Palestrantes
palestrantes:
  - us:
    nome: Marcelo Bião
    imagem: assets/palestrantes/marcelo.png
    vinculo: Mandacaru Hackerspace
    texto: Sou Master das culinárias do Mandacaru Hackerspace. Faço um ótimo arroz com calabresa, mas esqueço na geladeira por uma semana. 
  - us:
    nome: Sérgio Matos
    imagem: assets/palestrantes/sergio.png
    vinculo: Mandacaru Hackerspace
    texto: Sou Master dos paranauês do Mandacaru Hackerspace. De vez em quando, eu esqueço de enviar a arte dos eventos.
  - us:
    nome: Vitor Cardim
    imagem: assets/palestrantes/vitor.png
    vinculo: Mandacaru Hackerspace
    texto: Sou Master of Cards do Mandacaru Hackerspace. Comi uma pizza de 3 queijos, fui procurar o banheiro e acabei parando em Uberlândia.
  - us:
    nome: Leo Melo
    imagem: assets/palestrantes/leonardo.png
    vinculo: Mandacaru Hackerspace
    texto: Sou Master arteiro do Mandacaru Hackerspace. Sou o maior nome representante do terraplanismo no globo. 
  - us:
    nome: Fábio Bispo
    imagem: assets/palestrantes/fabio.png
    vinculo: Mandacaru Hackerspace
    texto: Sou CEO do Mandacaru Hackerspace. Procuro meios de invadir a conta do telegram do Ministro da Justiça. Fogo nos racistas!

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
